version: '3.8'

services:
  volley-stat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: volley-stat-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
